### ISSUE TITLE
Detect the word underneath cursor, when nothing is selected.

### ISSUE THREAD

**Issue by munyabe** [munyabe/CaseConverter#3]
@BrainCrumbz wrote on #2 :

It could be a nice-to-have feature if extension could detect the word underneath cursor, when nothing is selected. Basically the same happening as when you press F2 to perform rename refactoring. Just our 2 cents. Thank you!

**Comment by BrainCrumbz** [comment]
It looks like the change should occur in [ConvertCaseCommand.Execute()](https://github.com/munyabe/CaseConverter/blob/2a49edc12366ac42e8274ef3c767ad4897d6760b/CaseConverter/ConvertCaseCommand.cs#L45) method, but the only API we could find on word selection are the following:
- [TextSelection.WordLeft](https://msdn.microsoft.com/en-us/library/envdte.textselection.wordleft.aspx)
- [TextSelection.WordRight](https://msdn.microsoft.com/en-us/library/envdte.textselection.wordright.aspx)

In added (VB) example it seems like it's enough to start from current insertion point, then select the word before/after that point (if any). It does not specify what happens when insertion point is **in the middle of** a word.

Sorry for not being able to help more at the moment (e.g. with a PR).

**Comment by munyabe** [comment]
Nice try! Probably I did it at ae6b8ce.
After testing a little more, new update will probably come in the next few days.

**Comment by munyabe** [comment]
I had a fix at v1.3!
